name: Android Main Pipeline (Post-Merge)

permissions:
  contents: write 
  
on:
  push:
    branches: [ "master" ]

concurrency:
  group: android-master-${{ github.ref_name }}
  cancel-in-progress: true

jobs:

  # ===============================
  # BUILD APK
  # ===============================
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Assemble Staging APK
        run: |
          ./gradlew assembleStagingDebug -PSTAGING_URL="${{ secrets.STAGING_URL }}"

      - name: Upload Staging APK
        uses: actions/upload-artifact@v4
        with:
          name: staging-apk
          path: app/build/outputs/apk/staging/debug/app-staging-debug.apk

  # ===============================
  # SYSTEM INTEGRATION TEST (APPIUM)
  # ===============================
  sit-appium:
    name: SIT (Appium)
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 45
    continue-on-error: true

    steps:
      - name: Checkout Appium Tests
        uses: actions/checkout@v4
        with:
          repository: ysriser/BinItRightAppiumScripts
          path: appium-tests

      - name: Download Staging APK
        uses: actions/download-artifact@v4
        with:
          name: staging-apk
          path: apk

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'


      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Appium
        run: |
          npm install -g appium
          appium driver install uiautomator2


      - name: Start Android Emulator and Run Appium Tests
        uses: reactivecircus/android-emulator-runner@v2
        env:
          ANDROID_EMULATOR_WAIT_TIME_BEFORE_KILL: 300
        with:
          api-level: 29
          target: default
          arch: x86
          profile: pixel
          emulator-boot-timeout: 900
          emulator-options: >
            -no-window
            -no-audio
            -no-snapshot
            -gpu swiftshader_indirect
          disable-animations: true
          script: |
            adb devices
          
            echo "Starting Appium..."
            appium --log-level error > appium.log 2>&1 &
            sleep 20

            adb install apk/app-staging-debug.apk || true
            
            mvn -f appium-tests/pom.xml clean test -Dapk.path=$GITHUB_WORKSPACE/apk/app-staging-debug.apk


      - name: Upload Appium reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: appium-logs
          path: |
            appium-tests/target/surefire-reports/**
            appium.log
  # ===============================
  # BUILD PRODUCTION APK
  # ===============================
  build-production:
    name: Build Production APK
    needs: sit-appium
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Assemble Production Release APK
        run: |
          ./gradlew assembleProductionRelease -PPROD_URL="${{ secrets.PROD_URL }}"

      - name: Upload Production APK
        uses: actions/upload-artifact@v4
        with:
          name: production-apk
          path: app/build/outputs/apk/production/release/app-production-release-unsigned.apk

  # ===============================
  # TAG APK AS PRODUCTION
  # ===============================
  tag-production:
    name: Tag APK as Production
    needs: build-production
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Calculate Version
        id: calc
        run: |
          BASE="v1.0."
          git fetch --tags
  
          LATEST=$(git tag -l "${BASE}*" | sort -V | tail -n 1)
  
          if [ -z "$LATEST" ]; then
            NEXT=1
          else
            NUM=${LATEST#$BASE}
            NEXT=$((NUM + 1))
          fi
  
          TAG="${BASE}${NEXT}"
          echo "NEW_TAG=$TAG" >> $GITHUB_ENV
          echo "Next version: $TAG"

      - name: Tag Commit
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "$NEW_TAG"
          git push origin "$NEW_TAG"
