name: Android CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  #Ô∏è STAGE 1: BUILD
  build:
    name: BUILD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Assemble Debug APK
        run: ./gradlew assembleDebug

      # We MUST upload the APK here so Job 5 can download it
      - name: Save APK for SAST
        uses: actions/upload-artifact@v4
        with:
          name: compiled-apk
          path: app/build/outputs/apk/debug/app-debug.apk

  # STAGE 2: LINT (Quality Gate)
  lint:
    name: LINT
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Android Lint
        run: ./gradlew lintDebug
      - name: Upload Lint Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: app/build/reports/lint-results-debug.html

  # STAGE 3: UNIT (Logic Gate)
  unit-tests:
    name: UNIT
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Run JUnit Tests
        run: ./gradlew testDebugUnitTest
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: app/build/test-results/testDebugUnitTest/

  # BOX 4: SAST (The Gatekeeper)
  sast-scan:
    name: üõ°Ô∏è SAST Scan
    needs: [lint, unit-tests, sca-scan]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run MobSF Enforcer
        uses: MobSF/mobsfscan@main
        with:
          # Pointing to '.' will automatically pick up your '.mobsf' config
          args: '.'

      # OPTIONAL: Only if you want to see the report in the GitHub Security Tab
      - name: Upload SARIF file
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sast-results
          path: results.sarif